### ISSUE TITLE
Huxley and Huxley 2 seems to be throwing an Error 500 for any departure/arrival query

### ISSUE THREAD

**Issue by jasonkapadia** [jpsingleton/Huxley2#15] opened 2022-12-08 18:05 UTC
**Describe the bug**
Error 500 being thrown for any request

**To Reproduce**
Try to access any huxley / huxley2 instance query a stop for departures/arrivals.
eg: https://huxley2.azurewebsites.net/departures/bhm 

**Expected behavior**
Return a valid response, however all we get is an error 500.

**Desktop (please complete the following information):**
Any OS/Browser/Platform

**Additional context**
Huxley 2 and the original Huxley seem to be having the same issue.

**Comment by jpsingleton** [comment] 2022-12-09 13:50
Thanks for the bug report. This looks like a dupe of https://github.com/jpsingleton/Huxley2/issues/13 / https://github.com/jpsingleton/Huxley2/pull/14 so closing.

**Closed by jpsingleton** 2022-12-09 13:50 UTC
